### ISSUE TITLE
AnsiballZ_setup.py left behind in container /tmp

### ISSUE THREAD

**Issue by jordemort** [ansible-community/ansible-bender#139]
When I build a container with ansible-bender it leaves behind an AnziballZ_setup.py in a directory in `/tmp` - it'd be nice if ansible-bender cleaned this up.

**Comment by TomasTomecek** [comment]
Wow, this is pretty interesting. Especially since /tmp is meant to be tmpfs.

Unfortunately, I can't reproduce, could you please show me your base image, playbook
and how you build the image? I tried to repro using [ths
playbook](https://github.com/ansible-community/ansible-bender/blob/master/tests/data/basic_playbook.yaml)
and alpine (`docker.io/library/python:3-alpine`) as a base.

**Comment by jordemort** [comment]
I am using things in a rather weird way :D

Here's my playbook:

```
---
- name: Build a container from an imported stage1 debootstrap
  hosts: all
  vars:
    ansible_bender:
      cache_tasks: no
      layering: no

  tasks:

  - name: Make debootstrap script safe for containers
    replace:
      path: /debootstrap/debian-common
      regexp: '\bsetup_(proc|devices|dynamic_devices)\b'
      replace: '/bin/true'

  - name: Run second-stage debootstrap
    command: /debootstrap/debootstrap --second-stage

  # We aren't using the "apt" ansible module here because it wants to
  # automatically install python3-apt

  - name: Clean apt archives
    command: /usr/bin/apt-get clean

  - name: Clean apt lists
    command: /usr/bin/apt-get update
```

I'm running it against a tarball created with `debootstrap --foreign --variant=minbase` and then imported with `podman import`.

My command-line is something like:

```
ansible-bender --verbose build --no-cache
    --build-volumes /py:/py
    --python-interpreter /py/bin/python3.7m
    /app/ansible/debootstrap.yml
    registry.local/stage1 registry.local/stage2
```

`/py` contains a Python 3.7 build linked to be independent of the OS.
