### ISSUE TITLE
Use of environment variables in yaml

### ISSUE THREAD

**Issue by mchassy** [ansible-community/ansible-bender#169]
I am working on a little poc using ansible-bender on a local container to generate images and push them to a private docker registry. My aim is run everything using `docker exec` commands to run inside the container and to make my life easier I have an environment variable for the registry both on my localhost and when I run the ansible-bender container.
All of that works fine. For example the ansible-bender push  command can use the $REGNAME.
But when I want to generate the new image, I have to give the base image in the yaml file. And the base image sits on the same registry. So I put a var in the yaml file with a value of $REGNAME. That variable is never interpreted, which I will have to hard code the value. 
Is this a limitation of yaml in general or could you modify the code to parse environment variables?

**Comment by TomasTomecek** [comment]
Could you please share some more information with me because it's hard to imagine.

I'm pretty sure you should be able to use [env lookup](https://docs.ansible.com/ansible/latest/plugins/lookup/env.html) to access env vars in the vars section.

**Comment by mchassy** [comment]
Something like this
```
---
- name: test ansible-bender
  hosts: all
  vars:
    user_name: "Kevin"
    docker_uri: $MYENVAR
    ansible_bender:
      base_image: "{{ docker_uri }}/alpine:latest"
      working_container:
```

But of course, I hadn't thought of just using an ansible function to get the value.
Let me check and I will write back to tell you.
