### ISSUE TITLE
Not possible to set entrypoint on generated image

### ISSUE THREAD

**Issue by mchassy** [ansible-community/ansible-bender#192]
I have tried setting the entrypoint to an image in the following ways ways:
1. Via configuration - using these three variations
```
    ansible_bender:
      base_image: "{{ lookup('env','DOCKER_URI') }}/alpine:latest"
      working_container:
        working_dir: /prj/kudos
        volumes:
          - '{{ playbook_dir }}:/src'

      target_image:
        name: kudos-prod
        entrypoint: dumb-init /entrypoint.sh
        entrypoint: "dumb-init /entrypoint.sh"
        entrypoint: ["dumb-init", "/entrypoint.sh"]
        labels:
          built-by: '{{ ansible_user }}'
```
I tried all three of the above. They cause no error, but the entrypoint script is not executed unless I explicitly force in the run command: `docker run --rm -it --entrypoint $DOCKER_URI/kudos-prod`

2. As an additional  `--entrypoint` parameter for the `ansible-bender` command like this:
```
ansible-bender build  --entrypoint "/entrypoint.sh" ./build/config.yml
```
which give the following error:
```
(env) ansible-bender build  --entrypoint "/entrypoint.sh" ./build/config.yml
usage: ansible-bender [-h] [-v] [--debug] [--database-dir DATABASE_DIR]
                      {build,build-inside-openshift,list-builds,get-logs,inspect,push}
                      ...
ansible-bender: error: unrecognized arguments: --entrypoint
```

What am I doing wrong here?
