### ISSUE TITLE
Ability to set entrypoint on working container

### ISSUE THREAD

**Issue by seidzade** [ansible-community/ansible-bender#198]
Currently, only target_image context supports the setup of the entrypoint, which is affects only "production" image.

In cases, where base image already has an entrypoint, ansible-bender will stuck during the build, due endless process running by container.

This problem can be solved by adding the ability to setup entrypoint for working container , this entrypoint will override the entrypoint of the base image:
```
 vars:
    ansible_bender:
      working_container:
        entrypoint: <an_entrypoint>
```
