### ISSUE TITLE
There was an error during execution: Additional properties are not allowed ('entrypoint' was unexpected)

### ISSUE THREAD

**Issue by LordBonkerz** [ansible-community/ansible-bender#219]
Hello all,

Problems building with ansible-bender. I have took on someone else's playbook who is no longer here..  This used to work but now it doesn't due the error you see in the subject.

So I have no clue, to why :)  Google gives no joy!

stackstorm2.yaml:
```
---
- name: stackstorm container
  hosts: all
  vars:
    ansible_bender:
      base_image: stackstorm/stackstorm:2.7.0c
      entrypoint: ls
      target_image:
        entrypoint: ls
        name: stackstorm
        working_dir: /src
        labels:
          built-by: '{{ ansible_user }}'
        environment:
           ST2_USER: DUMMY
           ST2_PASSWORD: xxxxxx
    ductus_packs_version: v1.6.0
    ductus_core_version: v1.2.0
  tasks:
  - name: ductus-core
    tags: ductus-core
    import_role:
        name: ductus-core
  - name: ductus-packs
    tags: ductus-packs
    import_role:
        name: ductus-packs
  - name: access
    tags: access
    import_role:
        name: access
  - name: common
    tags: common
    import_role:
        name: common
```

```
ansible-bender build ./stackstorm2.yaml 

There was an error during execution: Additional properties are not allowed ('entrypoint' was unexpected)
```

ansible-bender -V
0.8.1

docker version
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea838
 Built:             Wed Nov 13 07:29:52 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea838
  Built:            Wed Nov 13 07:28:22 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

ansible --version
ansible 2.9.4
  config file = None
  configured module search path = ['/home/vagrant/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.9 (default, Nov  7 2019, 10:44:02) [GCC 8.3.0]

podman -v
podman version 1.6.2

buildah --version
buildah version 1.10.1 (image-spec 1.0.1, runtime-spec 1.0.1-dev)

**Comment by LordBonkerz** [comment]
`---
- name: stackstorm container
  hosts: all
  vars:
   ansible_bender:
     base_image: stackstorm/stackstorm:2.7.0c
      entrypoint: ls
     target_image:
       entrypoint: ls
       name: stackstorm
       working_dir: /src
       labels:
         built-by: '{{ ansible_user }}'
       environment:
          ST2_USER: DUMMY
          ST2_PASSWORD: password
   ductus_packs_version: v1.6.0
   ductus_core_version: v1.2.0
  tasks:
  - name: ductus-core
    tags: ductus-core
    import_role:
        name: ductus-core
  - name: ductus-packs
    tags: ductus-packs
    import_role:
        name: ductus-packs
  - name: access
    tags: access
    import_role:
        name: access
  - name: common
    tags: common
    import_role:
        name: common`

**Comment by LordBonkerz** [comment]
`---
- name: stackstorm container
  hosts: all
  vars:
   ansible_bender:
     base_image: stackstorm/stackstorm:2.7.0c
      entrypoint: ls
     target_image:
       entrypoint: ls
       name: stackstorm
       working_dir: /src
       labels:
         built-by: '{{ ansible_user }}'
       environment:
          ST2_USER: DUMMY
          ST2_PASSWORD: password
   ductus_packs_version: v1.6.0
   ductus_core_version: v1.2.0
  tasks:
  - name: ductus-core
    tags: ductus-core
    import_role:
        name: ductus-core
  - name: ductus-packs
    tags: ductus-packs
    import_role:
        name: ductus-packs
  - name: access
    tags: access
    import_role:
        name: access
  - name: common
    tags: common
    import_role:
        name: common`

**Comment by TomasTomecek** [comment]
Hey, thanks for taking time to open the issue and sorry for a late response - really busy lately.

You're using a feature which was committed to the repo in fall last year and my expectation was that it's released and fully functional. Apparently not, since I can reproduce locally. Let me take a closer look.

**Comment by TomasTomecek** [comment]
I can see the issue now: the problem is the entrypoint key under ansible_bender; this should work:
```yaml
---
- name: stackstorm container
  hosts: all
  vars:
    ansible_bender:
      base_image: stackstorm/stackstorm:2.7.0c
      target_image:
        entrypoint: ls
        name: stackstorm
        working_dir: /src
        labels:
          built-by: '{{ ansible_user }}'
        environment:
           ST2_USER: DUMMY
           ST2_PASSWORD: xxxxxx
    ductus_packs_version: v1.6.0
    ductus_core_version: v1.2.0
  tasks: ...
```
