### ISSUE TITLE
caching works incorrectly if with_items specified

### ISSUE THREAD

**Issue by ihanick** [ansible-community/ansible-bender#229]
The first run works correctly.
The second run returns:
```
ansible-bender --version
0.8.2.dev19+ga13178d

ansible-bender build playbook.yaml
TASK [Run a sample command] *******************************************************************************************************************************************************************
loaded from cache: '6ad04db0b455e5d908d45ef18c2213302e1ee18a08cd359e2c6dbb46152bc07e'
skipping: [bug-copy-cache-20200525-112800188925-cont] => (item=a)
skipping: [bug-copy-cache-20200525-112800188925-cont] => (item=b)
skipping: [bug-copy-cache-20200525-112800188925-cont] => (item=c)

TASK [Creates a file with contents] ***********************************************************************************************************************************************************
fatal: [bug-copy-cache-20200525-112800188925-cont]: FAILED! => {"changed": false, "checksum": "e23b0534d0708167023aba6f65ef83afe38d52df", "msg": "Destination directory /opt/b does not exist"}
loaded from cache: 'df1437da1fe6061c3551eeb1b2a93d4dc0a05ec8a6f880f399c0a077365d6d21'
```
playbook.yaml:
```yaml
---
- name: Demonstration of ansible-bender functionality
  hosts: all
  vars:
    ansible_bender:
      base_image: python:3-alpine

      working_container:
        volumes:
          - '{{ playbook_dir }}:/src'

      target_image:
        name: bug-copy-cache
        working_dir: /src
  tasks:
  - name: Run a sample command
    shell:
      cmd: 'mkdir /opt/{{item}};touch /opt/{{item}}/.empty'
      creates: /opt/{{item}}/.empty
    with_items:
      - a
      - b
      - c
  - name: Creates a file with contents
    copy:
      content: |
        First line
        Second line
      dest: /opt/b/file1
```
