### ISSUE TITLE
template task breaks caching system

### ISSUE THREAD

**Issue by tsuchm** [ansible-community/ansible-bender#230]
When using `template` task

```
- name: Put preferences for backported packages.
  template:
    src: preferences.j2
    dest: /etc/apt/preferences.d/backports
    owner: root
    group: root
    mode: 0644
```

with the following template

```
Package: *
Pin: release n={{ansible_distribution_release}}-backports
Pin-Priority: 500
```

ansible-bender judges the cached container imave is changed after this task, even if `ansible_distribution_relase` is not changed.

This behavior causes unnecessary actions after `template` task.
