### ISSUE TITLE
remove build volumes mount point empty dir when committing the final image

### ISSUE THREAD

**Issue by gzm55** [ansible-community/ansible-bender#235]
When building the image with build-time volumes, such as playbook-dir:/src, an empty dir `/src` will left in the final image. Can mount the build-time volumes in each `buildah run ...`  command, instead of in `buildah from` command, and at time of commit, execute another run command to remove all the empty mount point folders?

**Comment by TomasTomecek** [comment]
this is pretty interesting behaviour of buildah - I'm wondering if we should get some support from it here

**Comment by gzm55** [comment]
Now my own images use a workaround, putting the following task at the very last of the playbook:

```yaml
    # to clean up the mount point empty direcotires, we need:
    # - place this task at last of this play, that is, the 'buildah commit' will be called immediately
    # - ran by 'raw' module, then 'buildah umount' will not be inserted before commit
    # - provide SYS_ADMIN capacity
    # - each new mount point must be bind directly in /mnt directory
    # - /mnt contains only mount point directories
    #
    # to clean up dynamic mounted files by runtime engin, we also require SYS_ADMIN capacity
    - name: cleanup mount point directories
      changed_when: False
      vars:
        dy_mounts:
        - /run/.containerenv
        - /etc/resolv.conf
        - /etc/hosts
        - /etc/hostname
        cmds:
        - find /mnt -mindepth 1 -maxdepth 1 -exec umount {} + -exec rmdir {} +
        - ls -1 {{ dy_mounts | join(' ') }} 2>/dev/null | xargs -r umount
        - rm -f {{ dy_mounts | join(' ') }}
        - find /run -mindepth 1 -delete
      raw: sh -ec {{ cmds | join(' ; ') | quote }}
```

**Comment by gzm55** [comment]
Now my own images use a workaround, putting the following task at the very last of the playbook:

```yaml
    # to clean up the mount point empty direcotires, we need:
    # - place this task at last of this play, that is, the 'buildah commit' will be called immediately
    # - ran by 'raw' module, then 'buildah umount' will not be inserted before commit
    # - provide SYS_ADMIN capacity
    # - each new mount point must be bind directly in /mnt directory
    # - /mnt contains only mount point directories
    #
    # to clean up dynamic mounted files by runtime engin, we also require SYS_ADMIN capacity
    - name: cleanup mount point directories
      changed_when: False
      vars:
        dy_mounts:
        - /run/.containerenv
        - /etc/resolv.conf
        - /etc/hosts
        - /etc/hostname
        cmds:
        - find /mnt -mindepth 1 -maxdepth 1 -exec umount {} + -exec rmdir {} +
        - ls -1 {{ dy_mounts | join(' ') }} 2>/dev/null | xargs -r umount
        - rm -f {{ dy_mounts | join(' ') }}
        - find /run -mindepth 1 -delete
      raw: sh -ec {{ cmds | join(' ; ') | quote }}
```
