### ISSUE TITLE
introduce init command

### ISSUE THREAD

**Issue by TomasTomecek** [ansible-community/ansible-bender#61]
The command will add a template playbook with all the vars.

Edit: the expectation here is that a user would run `ansible-bender init` in the root of a git project. The command would create a new yaml file - an ansible playbook. The playbook would look like this:
```yaml
---
- name: Containerized version of $project
  hosts: all
  vars:
    a_variable: value
    # configuration specific for ansible-bender
    ansible_bender:
      base_image: fedora:latest
      target_image:
        # command to run by default when invoking the container
        cmd: /command.sh
        name: $project
      working_container:
        volumes:
        # mount this git repo to the working container at /src
        - "{{ playbook_dir }}:/src"
  tasks:
  - name: install dependencies needed to run project $project
    package:
      name:
      - a_package
      - another_package
      state: present
```

After the file is created on disk, ab should inform the user what happened and what are the next steps and how to run a build.
