### ISSUE TITLE
Support caching blocks

### ISSUE THREAD

**Issue by TomasTomecek** [ansible-community/ansible-bender#98]
One can [write blocks](https://docs.ansible.com/ansible/latest/user_guide/playbooks_blocks.html) in a playbook. It would be awesome if bender considered these as a single unit and cached them like it.

Use case:
```yaml
- block:
    dnf:
      name: python3-flask
      state: installed
    command: dnf clean all
```
